# Generated by Django 5.2.14 on 2026-06-04 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('product_id', models.UUIDField(db_index=True, help_text='Денормализовано для эффективного batch-запроса в B2B')),
                ('sku_id', models.UUIDField(db_index=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_items',
                'indexes': [models.Index(fields=['session_id'], name='cart_items_session_eb1d78_idx'), models.Index(fields=['user', 'sku_id'], name='cart_items_user_id_fc6ce3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_id__isnull', False), _connector='OR'), name='cart_identity_check'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'sku_id'), name='unique_user_sku'), models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'sku_id'), name='unique_session_sku')],
            },
        ),
    ]
