# Generated by Django 5.2.14 on 2026-06-05 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(db_index=True, unique=True)),
                ('address_id', models.UUIDField()),
                ('payment_method_id', models.UUIDField()),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PAID', 'Оплачен'), ('CREATED', 'Создан'), ('ASSEMBLING', 'Собирается'), ('DELIVERING', 'Доставляется'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменён'), ('CANCEL_PENDING', 'Ожидает отмены')], default='PAID', max_length=20)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.IntegerField()),
                ('line_total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ord.order')),
            ],
        ),
    ]
