# Generated by Django 5.2.14 on 2026-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.UUIDField(default=333),
            preserve_default=False,
        ),
    ]
